import { Book, ListCheck, Speakerphone } from "tabler-icons-react";

export const urls = {
  LOGIN: "/login",
  REGISTER: "/registro",
  INDEX: "/",
};

export const unprotectedURLs = [urls.LOGIN, urls.REGISTER];

const ogTagImageNoProtocol = `${process.env.NEXT_PUBLIC_DOMAIN}/images/logo.png`;

export const OG_TAGS = {
  url: `https://${process.env.NEXT_PUBLIC_DOMAIN}`,
  title: "Máster UDG",
  description: "Seguimiento ABPs máster UDG",
  image: {
    url: `http://${ogTagImageNoProtocol}`,
    secure_url: `http://${ogTagImageNoProtocol}`,
    alt: "Máster UDG",
  },
  twitterCard: "summary",
};

export const evaluations = [
  {
    name: "Responsabilidad",
    explanation:
      "Asiste y llega puntual a las sesiones (o se excusa correctamente), trae las tareas hechas, muestra interés durante la sesión, se implica en las discusiones, y toma el liderazgo cuando domina el tema.",
    icon: ListCheck,
  },
  {
    name: "Comunicación",
    explanation:
      "Explica de manera clara y concisa los conceptos estudiados, pregunta y replica con claridad en los debates, muestra empatía y respeta la opinión de los compañeros, y en general facilita la dinámica del grupo con sus intervenciones y preguntas",
    icon: Speakerphone,
  },
  {
    name: "Habilidades de Conocimiento",
    explanation:
      "Utiliza correctamente sus conocimientos previos para analizar y entender el caso, aporta fuentes de conocimiento relevantes para la discusión del caso, sabe profundizar y hacer un análisis crítico de los conceptos que se debaten, y es capaz de relacionar distintos conceptos desde un perspectiva multidisciplinar.",
    icon: Book,
  },
];

export const FAKE_COURSE_INFO = {
  id: 1,
  name: "Historia del Agua",
  order: 1,
  abps: [
    {
      id: 1,
      order: 1,
      teachers: [
        { id: 1, name: "Ignasi", email: "test@test.com" },
        { id: 2, name: "Albert Balagué Masfarré", email: "test@test.com" },
      ],
    },
    {
      id: 2,
      order: 2,
      teachers: [{ id: 1, name: "Ignasi", email: "test@test.com" }],
    },
    {
      id: 3,
      order: 3,
      teachers: [{ id: 1, name: "Ignasi", email: "test@test.com" }],
    },
    {
      id: 4,
      order: 4,
      teachers: [{ id: 1, name: "Ignasi", email: "test@test.com" }],
    },
  ],
};

export const FAKE_ABP_EVALUATIONS = [
  {
    id: 1,
    abpId: 2,
    studentId: 3,
    studentName: "Albert Camús Rodolfó i kalsdkf alksdf laksdj f",
    courseId: 4,
    courseName: "Historia del agua",
    asistencia: null,
    interes: null,
    informacion: null,
    interaccion: null,
    estudio: null,
    fuentes: null,
    analisis: null,
    notaFinal: null,
    chatTeacher1: "",
    chatStudent1: "",
    chatTeacher2: "",
  },
  {
    id: 2,
    abpId: 2,
    studentId: 3,
    studentName: "Jofre Rumbau Aligrós",
    courseId: 4,
    courseName: "Historia del agua",
    asistencia: null,
    interes: null,
    informacion: null,
    interaccion: null,
    estudio: null,
    fuentes: null,
    analisis: null,
    notaFinal: null,
    chatTeacher1: "",
    chatStudent1: "",
    chatTeacher2: "",
  },
  {
    id: 3,
    abpId: 2,
    studentId: 3,
    studentName: "Josep Llop Peris",
    courseId: 4,
    courseName: "Historia del agua",
    asistencia: null,
    interes: null,
    informacion: null,
    interaccion: null,
    estudio: null,
    fuentes: null,
    analisis: null,
    notaFinal: null,
    chatTeacher1: "",
    chatStudent1: "",
    chatTeacher2: "",
  },
  {
    id: 4,
    abpId: 2,
    studentId: 3,
    studentName: "Gregor Samsa",
    courseId: 4,
    courseName: "Historia del agua",
    asistencia: null,
    interes: null,
    informacion: null,
    interaccion: null,
    estudio: null,
    fuentes: null,
    analisis: null,
    notaFinal: null,
    chatTeacher1: "",
    chatStudent1: "",
    chatTeacher2: "",
  },
  {
    id: 5,
    abpId: 2,
    studentId: 3,
    studentName: "Maria Eulàlia Garcia",
    courseId: 4,
    courseName: "Historia del agua",
    asistencia: null,
    interes: null,
    informacion: null,
    interaccion: null,
    estudio: null,
    fuentes: null,
    analisis: null,
    notaFinal: null,
    chatTeacher1: "",
    chatStudent1: "",
    chatTeacher2: "",
  },
  {
    id: 6,
    abpId: 2,
    studentId: 3,
    studentName: "Roc Costa Monfort",
    courseId: 4,
    courseName: "Historia del agua",
    asistencia: null,
    interes: null,
    informacion: null,
    interaccion: null,
    estudio: null,
    fuentes: null,
    analisis: null,
    notaFinal: null,
    chatTeacher1: "",
    chatStudent1: "",
    chatTeacher2: "",
  },
  {
    id: 7,
    abpId: 2,
    studentId: 3,
    studentName: "Jordi Gironès",
    courseId: 4,
    courseName: "Historia del agua",
    asistencia: null,
    interes: null,
    informacion: null,
    interaccion: null,
    estudio: null,
    fuentes: null,
    analisis: null,
    notaFinal: null,
    chatTeacher1: "",
    chatStudent1: "",
    chatTeacher2: "",
  },
  {
    id: 8,
    abpId: 2,
    studentId: 3,
    studentName: "Pere Gumbau",
    courseId: 4,
    courseName: "Historia del agua",
    asistencia: null,
    interes: null,
    informacion: null,
    interaccion: null,
    estudio: null,
    fuentes: null,
    analisis: null,
    notaFinal: null,
    chatTeacher1: "",
    chatStudent1: "",
    chatTeacher2: "",
  },
  {
    id: 9,
    abpId: 2,
    studentId: 3,
    studentName: "Anna Romagosa Farigola",
    courseId: 4,
    courseName: "Historia del agua",
    asistencia: null,
    interes: null,
    informacion: null,
    interaccion: null,
    estudio: null,
    fuentes: null,
    analisis: null,
    notaFinal: null,
    chatTeacher1: "",
    chatStudent1: "",
    chatTeacher2: "",
  },
  {
    id: 10,
    abpId: 2,
    studentId: 3,
    studentName: "Paula Bonvehí",
    courseId: 4,
    courseName: "Historia del agua",
    asistencia: null,
    interes: null,
    informacion: null,
    interaccion: null,
    estudio: null,
    fuentes: null,
    analisis: null,
    notaFinal: null,
    chatTeacher1: "",
    chatStudent1: "",
    chatTeacher2: "",
  },
];
